### ISSUE TITLE
Incorrect handling of theme switch

### ISSUE THREAD

**Issue by StephanEggermont** [JurajKubelka/PharoSprint#18]
Switching the already open application from dark to light theme did not update the hidden tab 'All'

**Comment by JurajKubelka** [comment]
Hi @StephanEggermont!

Thanks for the report. I have opened issue [19980 FogBugz](https://pharo.fogbugz.com/f/cases/19980/Not-displayed-tabs-in-Glamour-are-not-updated-on-theme-change)

**Comment by StephanEggermont** [comment]
Please check with 60481

**Comment by JurajKubelka** [comment]
I have tried the steps to reproduce, published in the [case 19980](https://pharo.fogbugz.com/f/cases/19980/Not-displayed-tabs-in-Glamour-are-not-updated-on-theme-change), and the issue is still present. 

There were any changes that may improve the case?

**Comment by StephanEggermont** [comment]
Yes, TabExample was fixed.

**Comment by JurajKubelka** [comment]
OK. That's nice. But it does not fix this issue. It uses Glamour framework. But maybe the same fix could be applied to the Glamour.
